export const usernames = [
  "UndeadHunter",
  "ZombieSlayer",
  "CorpseEater",
  "BrainMuncher",
  "RottingFlesh",
  "GhoulGamer",
  "InfectedSurvivor",
  "WalkingDeadFan",
  "FleshFeaster",
  "ApocalypseHero",
  "ZombifiedZapper",
  "RottenCorpse",
  "UndeadEnthusiast",
  "LurchingLurker",
  "ZombieWhisperer",
];
